import os
import logging
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='{"level": "%(levelname)s", "module": "static_assets", "message": "%(message)s"}'
)
logger = logging.getLogger(__name__)

class StaticAssetGenerator:
    """
    Phase 7: Static Context Generation
    
    Ensures every repository has the required baseline 'Context Pack' files.
    If a file is missing, it generates it with standard defaults.
    """
    
    def __init__(self, repo_path: str):
        self.repo_path = Path(repo_path).resolve()
        self.docs_dir = self.repo_path / "docs"
        self.adr_dir = self.docs_dir / "adr"
        self.obs_dir = self.repo_path / "observability"

    def generate_all(self):
        """
        Checks and generates all static assets.
        """
        self._ensure_dirs()
        
        # 1. Context Boundary
        self._create_file(".llmignore", self._get_llmignore_content())
        
        # 2. AI Sitemap
        self._create_file("llms.txt", self._get_llmstxt_content())
        
        # 3. Ingestion Config
        self._create_file("repomix.config.json", self._get_repomix_content())
        
        # 4. Workflow Context
        self._create_file("CONTRIBUTING.md", self._get_contributing_content())
        
        # 5. Operational Context
        self._create_file("observability/metrics.md", self._get_metrics_content())
        
        # 6. Architecture Decision Record Template
        self._create_file("docs/adr/ADR-000-Template.md", self._get_adr_template_content())

    def _ensure_dirs(self):
        for d in [self.docs_dir, self.adr_dir, self.obs_dir]:
            d.mkdir(parents=True, exist_ok=True)

    def _create_file(self, rel_path: str, content: str):
        file_path = self.repo_path / rel_path
        if not file_path.exists():
            logger.info(f"Generating missing asset: {rel_path}")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content.strip())
        else:
            logger.debug(f"Asset exists, skipping: {rel_path}")

    # --- Templates ---

    def _get_llmignore_content(self) -> str:
        return """
# Context Boundary: Files excluded from AI ingestion
*.lock
package-lock.json
yarn.lock
tests/fixtures/**
test-data/**
*.min.js
*.css
*.map
*.svg
*.png
*.jpg
.env
.env.*
.DS_Store
__pycache__/**
node_modules/**
.git/**
"""

    def _get_llmstxt_content(self) -> str:
        return f"""# Context Map: {self.repo_path.name}

> Generated by Hybrid Scaffolding System

## Core Documentation
* [Architecture Overview](./architecture.md)
* [Domain Blueprint](./blueprint.md)
* [Source Scaffold](./scaffold.md)

## Operational Standards
* [Observability Metrics](./observability/metrics.md)
* [Contributing Workflow](./CONTRIBUTING.md)
"""

    def _get_repomix_content(self) -> str:
        return """{
  "output": {
    "style": "markdown",
    "filePath": "scaffold.md",
    "removeComments": true,
    "showLineNumbers": false,
    "topFilesLength": 20
  },
  "ignore": {
    "customPatterns": [
      "*.lock",
      "*.log",
      "node_modules/**",
      "dist/**",
      "build/**"
    ]
  }
}"""

    def _get_contributing_content(self) -> str:
        return """# Contributing Guide

## Git Strategy
1. **Branching:** Feature branches off `main`. Name: `feat/name` or `fix/name`.
2. **Commits:** Use Conventional Commits (e.g., `feat: add parser`).
3. **PRs:** Require tests and documentation updates.

## Context Pack Updates
If you modify code logic, you MUST run `Ctrl+Shift+B` to update `scaffold.md` and `architecture.md`.
"""

    def _get_metrics_content(self) -> str:
        return """# Operational Metrics

## Logging
Format: Structured JSON.
Fields: `level`, `timestamp`, `service`, `trace_id`, `message`.

## Thresholds
* **API Latency:** < 200ms
* **Error Rate:** < 1%
"""

    def _get_adr_template_content(self) -> str:
        return """# ADR-000: [Title]

**Status:** Proposed | Accepted | Deprecated

## Context
What is the problem? What are the constraints?

## Decision
What are we doing?

## Consequences
* **Pros:** ...
* **Cons:** ...
"""

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python static_assets.py <repo_path>")
        sys.exit(1)
    
    gen = StaticAssetGenerator(sys.argv[1])
    gen.generate_all()
    print(f"✅ Static assets generated for {sys.argv[1]}")